### ISSUE TITLE
`TargetRubyVersion` と gemspec 内の required_ruby_version の整合性が取れていないのを検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#11]
例えば、`.rubocop.yml`でTargetRubyVersionが 2.3 だけど、`foo.gemspec`で`required_ruby_version`が2.2に設定されていたらおかしいので、それを検出したい。

実装は単純になると思う。

**Comment by koic** [comment]
良さそうな Cop のアイデアありがとうございます。upstream の 5057 に Pull Request しました。

**Comment by pocke** [comment]
ありがとうございます！！  RubyConfでバタバタしているので、あとでちゃんと見ます

**Comment by koic** [comment]
こちらおマージされましたのでクローズします。 @pocke RubyConf でお忙しいところレビューありがとうございました。たいへん勉強になりました！

**Comment by pocke** [comment]
ありがとうございます！！！
