### ISSUE TITLE
`Style/StringLiterals` の symbol 版

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#12]
`"foo"`のようなリテラルはsingle quoteを使えと怒られるが、`:"foo-bar"`のようなリテラルは怒られないため、これを怒るCopが必要。

Style/StringLiterals をそのまま持ってくれば動くのかは、よくわからない。

**Comment by koic** [comment]
https://github.com/rubocop/rubocop/pull/9809 で実現されました。次にリリースされる RuboCop 1.16 あたりで導入される見込みです。
