### ISSUE TITLE
`Lint/Void` で lambda / procを検出する

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#14]
```ruby
def foo
  -> () {hogehoge}
  proc {fugafuga}
  lambda {barbar}
  x
end
```

このlambdaやprocは、実行されないため、Lint/Voidで検出されるべきです。
実装は、そんなに難しくないと思います。 https://github.com/bbatsov/rubocop/pull/4858 が入ってから実装に手を付けたほうがいいかも知れない。

**Comment by koic** [comment]
こちら RuboCop 1.40.0 で検知できるようにしました。
https://github.com/rubocop/rubocop/releases/tag/v1.40.0
