### ISSUE TITLE
gemspec 内で、重複したフィールドがある場合に検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#23]
```ruby
Gem::Specification.new do |s|
  # name が2回呼ばれているため、何かがおかしい
  s.name = 'rubocop'
  s.name = 'rubocop2'

  # add_runtime_dependency などは何回呼ばれても良い
  s.add_runtime_dependency('parallel', '~> 1.10')
  s.add_runtime_dependency('parser', '>= 2.3.3.1', '< 3.0')
end
```

実装
====

末尾が `=` で終わるメソッドが2回以上呼ばれていたら、警告を追加するように実装すると良いと思います。

ちゃんとやるならば、メソッドのレシーバが`Gem::Specification.new`のブロック引数で定義されていることを見る必要があるかも知れません。

**Comment by koic** [comment]
なるほど。これは間違って `gem push` したらなかなか悲しい感じになりそうですね。先日の `Gemspec` 部署 #11 つながりで取り組んでみます。

**Comment by pocke** [comment]
ありがとうございます :bowing_man: 

余談ですが、これは本来 rubygems かなにかが警告を出すべきなのでは、ともちょっと思っています。

```ruby
$ RUBYOPT='-w' gem build hogehoge.gemspec
hogehoge.gemspec:4: redefined specification name
```

現状警告が出ているか、とかはまったく見てません><

**Comment by koic** [comment]
RuboCop としては upstream の 5087 に Pull Request を出しました。

**Comment by koic** [comment]
こちら RuboCop の upstream におマージされましたので、RuboCop JP の Issue としてはクローズしますね。
