### ISSUE TITLE
Redundant cbase

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#3]
```ruby
A == ::A # Always true

class X
  A == ::A # Sometime false
end
```

トップレベルであればcbaseは要らないので、それを要らないよねって言うCopが欲しい。

実装は比較的簡単だと思う。トップレベルかどうかの判断が少し手間がいる(例えば、`Class.new do ... end` の際にどうするべきなのか、とか)と思うけど、考えることはそれくらい？
Auto Correctは実装してしまっても良さそう。

**Comment by koic** [comment]
こちら RuboCop 1.40.0 で導入された `Style/ConstantBase` cop で検出できると思います。
https://github.com/rubocop/rubocop/releases/tag/v1.40.0
