### ISSUE TITLE
ActiveSupportの`presence`を使うときれいに書けるコードを検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#30]
```
a.present? ? a : nil
a.blank? ? nil : a
```

上記のようなコードは、単に`a.presence`で置き換えることが出来ます。
また

```
a.present? ? a : b
```

は`a.presence || b`で置き換えることができます。

このようなコードを`presence`を使うようにうながすCopを作りたいです

**Comment by hkdnet** [comment]
タイトルのメソッド名が違いそうです？

**Comment by pocke** [comment]
> タイトルのメソッド名が違いそうです？

ありがとうございます、修正しました 👍

**Comment by wata727** [comment]
書いてみました。レビューお願いします 🙏 
https://github.com/bbatsov/rubocop/pull/5208

**Comment by pocke** [comment]
It was merged and released. Thanks @wata727 !
