### ISSUE TITLE
Make new cop aware of no newline at end of file

### ISSUE THREAD

**Issue by koic** [rubocop-hq/rubocop-jp#31]
POSIX におけるテキストファイルの定義に合わせてファイルの最後に改行を入れるようにする Cop があると良いかもしれません (EOF に改行がないときに GitHub のコード diff の最後に表示される赤丸) 。

参考: http://hiroakiuno.hatenablog.com/entry/20070409/p1

一方で Ruby と直接関係のない定義の話なので、RuboCop が持つべき Cop ではなく別のツールで検出するべき問題という考え方もあります。Rails アプリケーション開発を例に挙げても、Ruby 以外で例えば YAML ファイルも検査の対象となるため、殊更 RuboCop の役割ではない気がしてたりします。実用性の観点からアプリケーションで扱うテキストファイルのうち Ruby だけを特別視するのも違うかなと思うためです。

このあたりのご意見ご感想を聞いてみたいです。

**Comment by onk** [comment]
Layout/TrailingBlankLines がそれですかねー？

**Comment by pocke** [comment]
> Layout/TrailingBlankLines がそれですかねー？

https://github.com/bbatsov/rubocop/blob/5bbdfdd9dbecbfd627480a75d6a508c330d65b79/spec/rubocop/cop/layout/trailing_blank_lines_spec.rb#L46-L49

それっぽいですね。




> 一方で Ruby と直接関係のない定義の話なので、RuboCop が持つべき Cop ではなく別のツールで検出するべき問題という考え方もあります。Rails アプリケーション開発を例に挙げても、Ruby 以外で例えば YAML ファイルも検査の対象となるため、殊更 RuboCop の役割ではない気がしてたりします。実用性の観点からアプリケーションで扱うテキストファイルのうち Ruby だけを特別視するのも違うかなと思うためです。


この辺は、特別視するのもなーと思いつつ、RuboCopが全部入りになっていると楽だというのも分かるので、私は特にどっちがいいという意見は今の所もってないです…。



余談ですが、RuboCopの設定を .editorconfig に書き出そう、みたいなIssueが本家に上がっていたので、それにこのCopの設定も反映させるといい感じな気がします。

**Comment by koic** [comment]
なるほど。たしかに `Layout/TrailingBlankLines` Cop の役割でした。.editorconfig の情報についても、ありがとうございます！
