### ISSUE TITLE
Hash のインスタンスに対する map { |k, v| [k, v.foo] }.to_h を transform_values にする Cop

### ISSUE THREAD

**Issue by sinsoku** [rubocop-hq/rubocop-jp#33]
```rb
h = { a: 1, b: 2 }
h.map { |k, v| [k, v.to_s] }.to_h
```

上記のコードは transform_values で置き換えることができます。

```rb
h = { a: 1, b: 2 }
h.transform_values(&:to_s)
```

### map は Enumerable のメソッド

map メソッドでブロック引数が2つあれば、おそらく Hash のインスタンスだとは思うけど、
確定できないので false positive が発生しそうです。

### 使える環境

古い Ruby/Rails では使用できないメソッドなので、 Cop を作るときに注意が必要そう。

- Ruby 2.4.0 以上
  - https://docs.ruby-lang.org/ja/2.4.0/class/Hash.html#I_TRANSFORM_VALUES
- Rails 4.2.0 以上
  - 実装されたコミットはこれです https://github.com/rails/rails/commit/b2cf8b251aac39c1e3ce71bc1de34a2ce5ef52b1

**Comment by koic** [comment]
https://github.com/rubocop-hq/rubocop/pull/7663 で実現されているためクローズします。
