### ISSUE TITLE
初心者が .rubocop.yml を簡単に作れるように rubocop --init が欲しい

### ISSUE THREAD

**Issue by sinsoku** [rubocop-hq/rubocop-jp#34]
初心者が `.rubocop.yml` を作成するのは下記の理由で難しいと思いました。

- `.rubocop.yml` の話が `rubocop --help` や README に記載がない
- デフォルト値がどうなっているのか分からない
- 使えるオプションが分からない

設定値は GitHub 上の RuboCop のソースコードを見るしか（たぶん）知る方法がない。

## 提案

`$ rubocop --init` で基本的な yml を生成して上げて、基本的な設定項目を列挙して上げたら良いかなと思いました。
最近のRailsの `routes.rb` だと URL がコメントとして挿入されています。

```rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
```

GitHub 上の RuboCop の yml へのリンクを挿入してあげると、親切かもしれません。

**Comment by koic** [comment]
まずは `rubocop --init` で[コンフィグレーションへのリンク](https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md)を示す .rubocop.yml を生成するようにしました。
https://github.com/rubocop-hq/rubocop/pull/6928

基本的な設定項目として何を示すかといった選別が悩ましいため、上記 PR でこのイシューのすべての問題が解決するわけではないですが、これをベース別途検討という形でこのイシュー自体はクローズします。ナイスな提案ありがとうございました！
