### ISSUE TITLE
has_manyでthrough optionを使ってる場合のinverse_of optionについて

### ISSUE THREAD

**Issue by sachin21** [rubocop-hq/rubocop-jp#38]
```
has_many :foo_users
has_many :foos, through: :foo_users
```

してる際に`Rails/InverseOf`のcopに怒られるのはfalse positiveなのかしら。
throughの場合にinverse_of option付けるのは不可能だと思うのですけれど、最近のRailsでは出来るようになったんですかね(いやまさか)

- RuboCop: `0.52.0`
- Ruby:  `2.4.3`
- Rails: `5.1.4`

RuboCopの誤検出についてあまり詳しくないのでご意見ください・・

**Comment by onk** [comment]
pull/5297 で修正済みだと思う。
v0.52.1 に上げてみてください。

**Comment by sachin21** [comment]
@onk ありがとうございます。ぼくが確認した時期では修正が無かったので、助かりました 🙇
