### ISSUE TITLE
演算子をドットで呼び出すのを怒るCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#5]
```ruby
a.[]
a.+ b
```

Rubyでは演算子もメソッドなのでこういう呼び出し方が出来るが、これは一般的ではないスタイルなのでこのスタイルを書いていたら怒る。

実装は簡単なのかはよくわからない。

注意点
---

- `a.+(b).something` みたいなのは気軽にauto-correctすると死ぬ

**Comment by koic** [comment]
`Style/OperatorMethodCall` cop で対応しました。RuboCop 1.37.0 以上で利用可能です。https://docs.rubocop.org/rubocop/cops_style.html#styleoperatormethodcall
