### ISSUE TITLE
Rubocopをrequireしたい。

### ISSUE THREAD

**Issue by sagaekeiga** [rubocop-hq/rubocop-jp#50]
### 発生している問題
コンソール上で `require 'rubocop'` をすると、以下の文言が返ってきます。
```ruby
uninitialized constant RuboCop::AST::Parser (NameError)
```

### やりたいこと

rubocopが吐き出すメッセージをgithubのprのchecksのannotationsにpostしたいので
rubocopのインとアウト部分をRailsアプリ上でカスタマイズしようとしています。

### 補足

```
rubocop (0.36.0)
parser 2.6.2.0
```

よろしくお願いします。

**Comment by pocke** [comment]
報告ありがとうございます。

試せそうなこととしては、以下の2つがあるので、試していただけると良いと思います

* RuboCopのバージョンが古いので、最新 or 可能なかぎり新しいバージョンまで上げてみてください。現在の最新は v0.66.0 です。
* 見た感じparser gemが読み込めていないように見えます。なので、`require 'rubocop'` をする前に`require 'parser'`をすると解決するかもしれません。もしくはGemfileに`gem 'rubocop'`と`gem 'parser'`を両方書くと解決するかもしれません。

**Comment by koic** [comment]
こちら現在の最新の RuboCop (0.71.0) で再現しません。もし最新の RuboCop で再現してお困りの場合は改めてイシューを開いてください。
