### ISSUE TITLE
%記法での配列内に `_` が入っている要素がある場合は要素ごとに改行してほしい

### ISSUE THREAD

**Issue by meganemura** [rubocop-hq/rubocop-jp#52]
cop の提案です。

%w, %W, %i %I を利用する際に
https://docs.ruby-lang.org/ja/2.6.0/doc/spec=2fliteral.html#percent

```ruby
%w(value_a and value_b value_c_and_value_d)
```

のように `_` が含まれている要素がスペース区切りで横に並んでいると
要素の切れ目が読みづらいため、こういった場合は

```ruby
%w(
  value_a
  and
  value_b
  value_c_and_value_d
)
```
のように要素ごとに改行してあるほうが読みやすいと感じます。

**Comment by koic** [comment]
`_` を含んだ要素のあるなしがルールの基準というのはシンプルでなさそうに感じており、今回のケースはあまり気乗りはしないというが正直なところです。
例えば `_` を含んだ要素を持つ配列 a と、`_` を含んだ要素を持たない配列 b が同一ファイル上で並んでいた場合に見た目が変わることになると思うのですが、このあたり参入者へのルールへの分かりやすさとして疑問があります (良いか悪いかは置いておいて、例えば要素ごとに一貫して折り返すというのはルールとして分かりやすいとは思います) 。

もしかするとコーディングスタイルよりもエディタによる設定などでの解決が良い問題かもしれません。

**Comment by koic** [comment]
コアへの提案は難しいように思えます。もし引き続き関心がある場合は 3rd パーティーの Cop として実装していただくとかになりそうです。Gem として提供する場合は rubocop-extension-generator が役立つかもしれません。
https://github.com/rubocop-hq/rubocop-extension-generator

イシューとしてはクローズしますが、フィードバックありがとうございました。
