### ISSUE TITLE
すでに .rubocop.yml に require があるときの案内がほしい

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop-jp#53]
rubocop 0.71.0 の `Post-install message from rubocop` で
````
Post-install message from rubocop:
Rails cops will be removed from RuboCop 0.72. Use the `rubocop-rails` gem instead.

Put this in your `Gemfile`.

```rb
gem 'rubocop-rails'
```

And then execute:

```sh
$ bundle install
```

Put this into your `.rubocop.yml`.

```yaml
require: rubocop-rails
```

More information: https://github.com/rubocop-hq/rubocop-rails
````

と出ますが、すでに `.rubocop.yml` に `require: rubocop-performance` があると、そのまま `require: rubocop-rails` を足してもエラーになるので、どこかに追加の説明がほしいです。

メッセージの中に URL が出ているので、 <https://github.com/rubocop-hq/rubocop-rails> に書かれていると良さそうに思いました。

**Comment by koic** [comment]
フィードバックありがとうございます。類似のイシューが上がっていたこともあり考えてみます。
https://github.com/rubocop-hq/rubocop/issues/7104

**Comment by hkdnet** [comment]
サンプルの表記が配列になっているだけでも察しやすくなるかも？と思いました。

**Comment by koic** [comment]
https://github.com/rubocop-hq/rubocop-rails ならびに https://github.com/rubocop-hq/rubocop-performance の README.md に追記しました。
