### ISSUE TITLE
auto correct でのエラー時に処理中のファイル名も出してほしい

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop-jp#55]
https://github.com/rubocop-hq/rubocop/issues/7165 や https://github.com/rubocop-hq/rubocop/issues/7167 の原因を調べる時に、バックトレースの

```
rubocop-0.71.0/lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb
```

をみて Naming/RescuedExceptionsVariableName cop らしいというのはすぐにわかるので、 

```
rubocop --only Naming/RescuedExceptionsVariableName
```

で auto correct ではないチェックの実行結果から該当しそうなファイルを探して最小の再現コードを作る、ということをしたのですが、ファイルを探すのが二度手間で大変なので、エラーメッセージで一緒に処理中のファイル名を出してほしいです。

**Comment by pocke** [comment]
私も欲しかったので実装してみました。
https://github.com/pocke/rubocop/commit/58277a93ed81d37e951c2fbf91f131eadbc788e0
とりあえず動きますが、テストがなかったり(たぶん)RuboCopに怒られるコードになっているので、そのへんをまとめてからPRにしようと思います。

**Comment by pocke** [comment]
auto-correctでもファイル名が出るようになりました 🎉
