### ISSUE TITLE
rspecのnot_to/to_notを統一したい

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop-jp#57]
rspec の not_to と to_not はどちらでも良いとなっていることが多くて、実際にはファイル単位では統一されていることが多くて、プロジェクトの中では混在してしまうことがあるように思っています。

デフォルトではどちらでも良いと思うのですが、どちらかに統一したいと思ったときに rubocop でチェックできると便利そうだと思ったのですが、どうでしょうか?

**Comment by sinsoku** [comment]
rubocop-rspec に NotToNot というルールがあります。
https://github.com/rubocop-hq/rubocop-rspec/blob/v1.33.0/lib/rubocop/cop/rspec/not_to_not.rb

こちらを使ってみるのはいかがでしょうか。

**Comment by koic** [comment]
はい。RuboCop RSpec の `RSpec/NotToNot` cop を使うのが良いようです。
デフォルトでは `EnforcedStyle: not_to` で有効になっており、`EnforcedStyle: to_not` にもカスタマイズ可能です。
https://github.com/rubocop-hq/rubocop-rspec/blob/v1.33.0/config/default.yml#L321-L328
