### ISSUE TITLE
Layout/DefEndAlignment は auto correct に非対応?

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop-jp#58]
Layout/DefEndAlignment は auto correct に非対応なのでしょうか?

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/DefEndAlignment をみると `#autocorrect(node)` があるので対応してそうにみえるのですが、何か他にも auto correct されるための条件があるのでしょうか?

```
% cat a.rb
def m
  :m
 end
% rubocop -V
0.73.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
% rubocop -a
Inspecting 1 file
W

Offenses:

a.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
def m
^
a.rb:5:2: W: Layout/DefEndAlignment: end at 5, 1 is not aligned with def at 3, 0.
 end
 ^^^

1 file inspected, 2 offenses detected, 1 offense corrected
% cat a.rb
# frozen_string_literal: true

def m
  :m
 end
```

**Comment by pocke** [comment]
`DefEndAlignment#autocorrect`が呼んでいる`AlignmentCorrector.align_end`を見ると、lambdaではなくfalseを返すケースがあるので、falseが返った場合はauto-corectがされないようになっていますね。


https://github.com/rubocop-hq/rubocop/blob/cbc6ec38b7c1a62f8728b4c9dc7e472414bd02b2/lib/rubocop/cop/layout/def_end_alignment.rb#L64-L70

https://github.com/rubocop-hq/rubocop/blob/cbc6ec38b7c1a62f8728b4c9dc7e472414bd02b2/lib/rubocop/cop/correctors/alignment_corrector.rb#L30-L37


ちゃんと見てはいませんが、上げてもらったコードはauto correctされてほしいように見えるので、バグかなと思います。



---


余談ですが、AlignmentCorrectorがクラスのインスタンス変数を使っていてちょっとお行儀悪いですね。多分現状バグってはいないけどちょっと気になる。。

**Comment by koic** [comment]
`Layout/DefEndAlignment` はデフォルトで `AutoCorrect: false` となっているため auto-correct は無効化されています。
https://github.com/rubocop-hq/rubocop/blob/v0.73.0/config/default.yml#L452

少し歴史を見たところ、期待どおりにキーワードと `end` がマッチできるか分からないというのがデフォルトで `AutoCorrect: false` としている当時の理由に見えます。
https://github.com/rubocop-hq/rubocop/pull/1789

**Comment by koic** [comment]
> #autocorrect(node) があるので対応してそうにみえるのですが、何か他にも auto correct されるための条件があるのでしょうか?

`AutoCorrect: true` と指定すると auto-correct が有効化されると思います。

```yaml
# .rubocop.yml
Layout/DefEndAlignment:
  AutoCorrect: true
```

**Comment by pocke** [comment]
あー嘘を書いていてすみません。koicさんのが正しいですね。

> 少し歴史を見たところ、期待どおりにキーワードと end がマッチできるか分からないというのがデフォルトで AutoCorrect: false としている当時の理由に見えます。


そうですね。。思い出したことを追記しておきます。
もともとこのCopはLint departmentにいました。なのでバグを検出するCopだとみなされていました。
defとendがずれている原因は次の2つが考えられて、

* 単にスタイルが崩れている
* 人間がdefとendの対応を誤ってインデントさせていて、インデントとdef-endの範囲がずれている

で、RuboCopがこの2つのどちらの問題なのか判断するのは無理で、2つ目のケースを修正したところで結局コードは間違ったままになってしまうので、auto-correctはfalseにしようという感じだったと思います。
