### ISSUE TITLE
a = a を検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#6]
代入の右辺で代入される変数を使用すると、それは必ずnilなのでなんらかの間違いである可能性が高い。
そのため、そのような代入を検出するCopが欲しい

```ruby
a = a # 右辺のaは常にnil
a = x do
  a # このaは常にnil
end
```

これは、実装が大変だとおもう(たぶんね)。VariableForceとか見ると答えがあるかも知れないけど、私もよく知らない。

**Comment by koic** [comment]
`Lint/SelfAssignment` cop で実現されているためクローズします。RuboCop 0.89 以上で利用可能です。
https://docs.rubocop.org/rubocop/1.37/cops_lint.html#lintselfassignment

ただし、以下のケースはサポートされていなさそうで、別途拡張できそうです。

```ruby
a = x do
  a # このaは常にnil
end
```

**Comment by pocke** [comment]
Issueの整理ありがとうございます 🙏 

> ```ruby
> a = x do
>   a # このaは常にnil
> end
> ```


改めて考えてみると、これは必ずしもこうはならなさそうですね。


```ruby
a = Thread.new do
  sleep 0.1
  p a
  # => #<Thread:0x0000000102f176d0 /path/top/test.rb:1 run>
end

a.join
```

このブロックが`a`変数が初期化される前にだけ呼ばれるのかを判定するのは、静的には難しそうな気がするので、拡張も難しそうな気がしています 💭
