### ISSUE TITLE
一部のファイルやファイルの中の一部だけ設定を変えたい

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop-jp#62]
たとえば `Layout/HashAlignment` でほとんどは `key` のままにしたいけれど、一部だけ `table` としたいことがあったのですが、今は一部だけ無効にする、という設定しかできなさそうでした。

**Comment by koic** [comment]
特定のパスに対して `EnforcedStyle` (`EnforcedHashRocketStyle`) の適用を行うというのは、config/default.yml (.rubocop.yml) の設定について、互換性の維持と複雑性を抑えた設計と実装が必要そうですぐの解決は難しいかもしれません。

代替になるのですが、[`Layout/HashAlignment ` は `AllowMultipleStyles` がサポートされている](https://github.com/rubocop-hq/rubocop/blob/v1.0.0/config/default.yml#L736)ので、サポートしたい複数のスタイルを設定することで解決できる可能性があります。以下は RuboCop 自体での設定です。
https://github.com/rubocop-hq/rubocop/blob/v1.0.0/.rubocop.yml#L69-L75

また手前味噌になりますが私のプレゼンテーションから `AllowMultipleStyles` についての抜粋です。
https://speakerdeck.com/koic/default-dot-yml-for-rubocop?slide=72

**Comment by koic** [comment]
同じ機能提案が https://github.com/rubocop/rubocop/issues/8580 として upstream に出ているためこちらはクローズします。
