### ISSUE TITLE
generotorつくる

### ISSUE THREAD

**Issue by Popotanu** [rubocop-hq/rubocop-jp#63]

**Comment by koic** [comment]
rubocop リポジトリへのディスカッションは英語で行いますので、タイトルをもとに日本語でのイシューで扱う rubocop-jp に移行しました。

RuboCop 公式としては新しい Cop を作る場合は `new_cop` という Rake タスクを用意しています。
https://docs.rubocop.org/rubocop/1.0/development.html#create-a-new-cop

また Gem として作成する場合のディレクトリレイアウトの作成に向けては以下のジェネレータがあります。
https://github.com/rubocop-hq/rubocop-extension-generator

既存のジェネレータの紹介に代えてクローズしますが、これら以外を目的としている場合はコメントにてフィードバックしてください。
