### ISSUE TITLE
Rubocop 1.46.0 からメモリ使用量が増えた

### ISSUE THREAD

**Issue by krororo** [rubocop-hq/rubocop-jp#67]
Rubocop 1.46.0 にアップデートしたところ 1.45.1 と比べてメモリ使用量が30%ほど増えていました。
そのため CI で動かしていた rubocop がメモリ不足によって落ちるようになってしまい困っています。
並列実行をやめたり CI 環境のメモリを増やして暫定対処としたのですが、 rubocop 側でメモリ使用量改善はできるでしょうか？

原因を探してみると以下の PR で増えているようでした。
* https://github.com/rubocop/rubocop/pull/11603

メモリプロファイルを取ってみたので添付します。
[rubocop-memory_profiler-1.45.1.txt](https://github.com/rubocop/rubocop-jp/files/10856337/rubocop-memory_profiler-1.45.1.txt)
[rubocop-memory_profiler-1.46.0.txt](https://github.com/rubocop/rubocop-jp/files/10856338/rubocop-memory_profiler-1.46.0.txt)

```
$ rubocop -V
1.46.0 (using Parser 3.2.1.0, rubocop-ast 1.27.0, running on ruby 3.1.2) [arm64-darwin21]
  - rubocop-performance 1.16.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.18.1
```

**Comment by koic** [comment]
https://github.com/rubocop/rubocop/issues/11657 で報告された問題と同様のようですので、RuboCop 1.48.0 で解決されていると思います。アップグレードしてお試しください。
https://github.com/rubocop/rubocop/releases/tag/v1.48.0

**Comment by krororo** [comment]
ありがとうございます！ 1.48.0 で解決していることを確認しました！
