### ISSUE TITLE
破壊的メソッドの再代入を検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#7]
```ruby
foo = foo.concat([bar, baz])
```

`Array#concat`は破壊的メソッドなので、再代入する必要はない。
false positiveが気になるけど、Ruby標準と同名で違うインターフェースのメソッドを定義するやつが悪いので、気にしない。

同様の例に、`gsub!`とかbangが付いたメソッド群もある。

**Comment by koic** [comment]
`Style/RedundantSelfAssignment` cop で実現されているためクローズします。RuboCop 0.90 以上で利用可能です。
https://docs.rubocop.org/rubocop/1.37/cops_style.html#styleredundantselfassignment
