### ISSUE TITLE
Lint/NumericOperationWithConstantResultが間違った自動修正をすることがある

### ISSUE THREAD

**Issue by linyclar** [rubocop-hq/rubocop-jp#70]
## バージョン
```shell-session
# ruby --version
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [aarch64-linux]
# rubocop --version
1.69.1
```

## バグ内容

算術演算のみを想定したCopのようですが、Arrayなどの場合でも適用されてしまうため間違った結果になります。

```ruby
# 実行前
class Hoge
  def hoge
    aaa = [1]
    aaa -= aaa

    aaa # => []
  end
end

# rubocop --enable-pending-cops -a hoge.rb
# を実行した後
class Hoge
  def hoge
    0

    # => []
  end
end
```

`[1] - [1]`の結果は `[]` なので、戻り値が変わってしまっています。

なので、少なくとも`rubocop -a`ではなく`rubocop -A`で自動修正されるCopかと思います。

## 提案

> This is almost always a mistake (or just left after debugging, probably) or just redundant code.
https://github.com/rubocop/rubocop/issues/11191

> These are probably mistakes or leftover from debugging, so flag and optionally remove them.
https://github.com/rubocop/rubocop/pull/13074

間違いやデバッグの残りのコードを想定されているのであれば、自動修正後に残る0や1も結局ゴミなのではないかという気がしています。
デバッグの残りやtypoなどで警告されると嬉しいケースは想像できましたが、0や1に自動修正されて嬉しいケースはちょっと思い浮かびませんでした。
なので、単に自動修正のサポートをやめても良いのではないかとも思います。

**Comment by koic** [comment]
rubocop/rubocop#13577 で解決したと思います。次のリリース (おそらく 1.70.0) がされたら検知されないようになる見立てです。

**Comment by linyclar** [comment]
ありがとうございます！🙇
