### ISSUE TITLE
必要のない行継続を検出するCop

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#8]
```ruby
def x
  foo && \
    bar
end
```

この場合`\`の行継続がなくても問題ないので、これを検出するCopがほしい(実装めんどそう)

**Comment by koic** [comment]
RuboCop 1.13.0 で導入された `Layout/RedundantLineBreak` cop で実現可能です。いまの実装だと `\` の継続行以外の改行も対象とする実装のため、おそらく期待している振る舞いに対して fat な気はします。そのあたり構成可能にできると使い勝手は期待するものに近づく気がします。
https://docs.rubocop.org/rubocop/1.13/cops_layout.html#layoutredundantlinebreak

(おそらく課題への解決として現状冗長な Cop ですが) イシューとしての問題は解決できると思うため、クローズします。
