### ISSUE TITLE
Metrics/LineLength にAuto-Correctを実装する

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#9]
Auto-Correct出来るケースはAuto-Correctしたい。

**Comment by koic** [comment]
RuboCop 1.4.0 のリリースあたりから `Layout/LineLength` の Auto-correction がデフォルトで有効になっていますので、こちらクローズします。
https://github.com/rubocop/rubocop/releases/tag/v1.4.0
